#!/usr/bin/env python3
"""Caijue Hub transcriber for Resources.

Reads caijuehub/caijue.toml, dispatches each rust-strategy entry to its
generator, and writes the generated strategy file into src/caijuehub/strategies/.

Usage:
    python3 caijuehub/transcribe.py
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CAIJUEHUB_DIR = REPO_ROOT / "caijuehub"

HEADER = """\
// ============================================================
// @generated by caijuehub/transcribe.py — DO NOT EDIT BY HAND.
// Edit the rules TOML declared in caijuehub/caijue.toml, then run:
//     python3 caijuehub/transcribe.py
// ============================================================
"""


def rust_bool(value: object) -> str:
    return "true" if value else "false"


def rust_str(value: object) -> str:
    return f'"{value}"'


def rust_f64(value: object) -> str:
    result = repr(float(value))
    return result if ("." in result or "e" in result or "E" in result) else f"{result}.0"


def generate_amd_sensor(rules: dict) -> str:
    smu = rules["smu"]
    fallback = smu["power_fallback"]
    gpu_page = rules["gpu_page"]
    cpu_page = rules.get("cpu_page", {})

    lines = [
        HEADER,
        "use crate::caijuehub::smu::AmdSmuMetrics;",
        "",
        "pub const SMU_ENABLED: bool = "
        f"{rust_bool(smu.get('enabled', True))};",
        "",
        "pub const SMU_QUERY_ON_AMD_MISSING_HWMON_POWER: bool = "
        f"{rust_bool(smu.get('query_when_amd_hwmon_power_missing', True))};",
        "",
        "pub const SMU_REFRESH_MODE: &str = "
        f"{rust_str(smu['refresh'])};",
        "",
        "pub const SMU_HELPER_NAME: &str = "
        f"{rust_str(smu['helper_name'])};",
        "",
        "pub const RYZENADJ_PATH: &str = "
        f"{rust_str(smu['ryzenadj_path'])};",
        "",
        "pub const POWER_VALUE_METRIC: &str = "
        f"{rust_str(fallback['value_metric'])};",
        "",
        "pub const POWER_CAP_METRIC: &str = "
        f"{rust_str(fallback['cap_metric'])};",
        "",
        "pub const GPU_PAGE_SHOW_SLOW_AND_STAPM_ROWS: bool = "
        f"{rust_bool(gpu_page.get('show_slow_and_stapm_rows', True))};",
        "",
        "pub const CPU_PAGE_SHOW_THROTTLE_ROW: bool = "
        f"{rust_bool(cpu_page.get('show_throttle_row', True))};",
        "",
        "pub const CPU_PAGE_SHOW_POWER_WALL_ROW: bool = "
        f"{rust_bool(cpu_page.get('show_power_wall_row', True))};",
        "",
        "pub const CPU_TEMPERATURE_FALLBACK: bool = "
        f"{rust_bool(cpu_page.get('temperature_fallback', True))};",
        "",
        "pub const CPU_THERMAL_LIMIT_C: f64 = "
        f"{rust_f64(cpu_page.get('thermal_limit_c', 95.0))};",
        "",
        "pub const CPU_POWER_WALL_RATIO: f64 = "
        f"{rust_f64(cpu_page.get('power_wall_ratio', 0.98))};",
        "",
        "#[must_use]",
        "pub fn fallback_power_usage(metrics: &AmdSmuMetrics) -> Option<f64> {",
        f"    metrics.metric(POWER_VALUE_METRIC)",
        "}",
        "",
        "#[must_use]",
        "pub fn fallback_power_cap(metrics: &AmdSmuMetrics) -> Option<f64> {",
        "    metrics.metric(POWER_CAP_METRIC)",
        "}",
        "",
        "#[must_use]",
        "pub fn fallback_cpu_temperature(metrics: &AmdSmuMetrics) -> Option<f64> {",
        "    metrics.temperature_c",
        "}",
        "",
    ]
    return "\n".join(lines)


def rust_u32(value: object) -> str:
    return str(int(value))


def generate_battery_threshold(rules: dict) -> str:
    cfg = rules["battery_threshold"]

    lines = [
        HEADER,
        "",
        "pub const HELPER_NAME: &str = "
        f"{rust_str(cfg['helper_name'])};",
        "",
        "pub const START_ATTRIBUTE: &str = "
        f"{rust_str(cfg['start_attribute'])};",
        "",
        "pub const END_ATTRIBUTE: &str = "
        f"{rust_str(cfg['end_attribute'])};",
        "",
        "pub const FALLBACK_START_ATTRIBUTE: &str = "
        f"{rust_str(cfg['fallback_start_attribute'])};",
        "",
        "pub const FALLBACK_END_ATTRIBUTE: &str = "
        f"{rust_str(cfg['fallback_end_attribute'])};",
        "",
        "pub const MINIMUM: u32 = "
        f"{rust_u32(cfg.get('minimum', 0))};",
        "",
        "pub const MAXIMUM: u32 = "
        f"{rust_u32(cfg.get('maximum', 100))};",
        "",
        "pub const STEP: u32 = "
        f"{rust_u32(cfg.get('step', 5))};",
        "",
        "pub const DISABLED_START: u32 = "
        f"{rust_u32(cfg.get('disabled_start', 0))};",
        "",
        "pub const DISABLED_END: u32 = "
        f"{rust_u32(cfg.get('disabled_end', 100))};",
        "",
        "pub const DEFAULT_START: u32 = "
        f"{rust_u32(cfg.get('default_start', 75))};",
        "",
        "pub const DEFAULT_END: u32 = "
        f"{rust_u32(cfg.get('default_end', 80))};",
        "",
        "pub const NOTIFY_UPOWER: bool = "
        f"{rust_bool(cfg.get('notify_upower', True))};",
        "",
    ]
    return "\n".join(lines)


def rust_str_slice(values: object) -> str:
    return "&[" + ", ".join(rust_str(value) for value in values) + "]"


def generate_process(rules: dict) -> str:
    ports = rules.get("ports", {})
    ownership = rules.get("ownership", {})
    grouping = rules.get("grouping", {})

    lines = [
        HEADER,
        "",
        "pub const PORT_PROTOCOLS: &[&str] = "
        + rust_str_slice(ports.get("protocols", ["tcp", "tcp6", "udp", "udp6"]))
        + ";",
        "",
        "pub const PORT_LISTEN_ONLY: bool = "
        f"{rust_bool(ports.get('listen_only', False))};",
        "",
        "pub const PORT_SEARCHABLE: bool = "
        f"{rust_bool(ports.get('searchable', True))};",
        "",
        "pub const SYSTEM_UID_MAX: u32 = "
        f"{rust_u32(ownership.get('system_uid_max', 999))};",
        "",
        "pub const ORPHAN_PARENT_PID: i32 = "
        f"{int(ownership.get('orphan_parent_pid', 1))};",
        "",
        "pub const DEFAULT_GROUPING: &str = "
        f"{rust_str(grouping.get('default', 'user'))};",
        "",
        "pub const GROUPING_ORDER: &[&str] = "
        + rust_str_slice(grouping.get("order", ["user", "app"]))
        + ";",
        "",
    ]
    return "\n".join(lines)


GENERATORS = {
    "amd-sensor-adjudication": generate_amd_sensor,
    "battery-charge-threshold": generate_battery_threshold,
    "process-adjudication": generate_process,
}


def main() -> int:
    index_path = CAIJUEHUB_DIR / "caijue.toml"
    if not index_path.exists():
        print(f"caijue.toml not found at {index_path}")
        return 1

    with index_path.open("rb") as handle:
        index = tomllib.load(handle)

    changed = []
    for entry in index.get("caijue", []):
        if entry.get("line_type") != "rust-strategy":
            continue

        generator = GENERATORS.get(entry["id"])
        if generator is None:
            print(f"skip {entry['id']}: no generator registered")
            continue

        rules_path = CAIJUEHUB_DIR / entry["rules"]
        if not rules_path.exists():
            print(f"skip {entry['id']}: rules {rules_path} not found")
            continue

        with rules_path.open("rb") as handle:
            rules = tomllib.load(handle)

        output_path = REPO_ROOT / entry["implementation"]
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(generator(rules), encoding="utf-8")
        print(
            f"generate {entry['implementation']} "
            f"(type={entry.get('line_type')} approval={entry.get('approval')})"
        )
        changed.append(
            {
                "rules": entry["rules"],
                "implementation": entry["implementation"],
                "approval": entry.get("approval", "auto"),
            }
        )

    print(f"audit: {changed}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
