#!/usr/bin/env python3
"""Caijue Hub transcriber for Resources.

Reads caijuehub/caijue.toml, dispatches each rust-strategy entry to its
generator, and writes the generated strategy file into src/caijuehub/strategies/.

Usage:
    python3 caijuehub/transcribe.py
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CAIJUEHUB_DIR = REPO_ROOT / "caijuehub"

HEADER = """\
// ============================================================
// @generated by caijuehub/transcribe.py — DO NOT EDIT BY HAND.
// Edit caijuehub/sensor-rules.toml, then run:
//     python3 caijuehub/transcribe.py
// ============================================================
"""


def rust_bool(value: object) -> str:
    return "true" if value else "false"


def rust_str(value: object) -> str:
    return f'"{value}"'


def generate_amd_sensor(rules: dict) -> str:
    smu = rules["smu"]
    fallback = smu["power_fallback"]
    gpu_page = rules["gpu_page"]

    lines = [
        HEADER,
        "use crate::caijuehub::smu::AmdSmuMetrics;",
        "",
        "pub const SMU_ENABLED: bool = "
        f"{rust_bool(smu.get('enabled', True))};",
        "",
        "pub const SMU_QUERY_ON_AMD_MISSING_HWMON_POWER: bool = "
        f"{rust_bool(smu.get('query_when_amd_hwmon_power_missing', True))};",
        "",
        "pub const SMU_REFRESH_MODE: &str = "
        f"{rust_str(smu['refresh'])};",
        "",
        "pub const SMU_HELPER_NAME: &str = "
        f"{rust_str(smu['helper_name'])};",
        "",
        "pub const RYZENADJ_PATH: &str = "
        f"{rust_str(smu['ryzenadj_path'])};",
        "",
        "pub const POWER_VALUE_METRIC: &str = "
        f"{rust_str(fallback['value_metric'])};",
        "",
        "pub const POWER_CAP_METRIC: &str = "
        f"{rust_str(fallback['cap_metric'])};",
        "",
        "pub const GPU_PAGE_SHOW_SLOW_AND_STAPM_ROWS: bool = "
        f"{rust_bool(gpu_page.get('show_slow_and_stapm_rows', True))};",
        "",
        "#[must_use]",
        "pub fn fallback_power_usage(metrics: &AmdSmuMetrics) -> Option<f64> {",
        f"    metrics.metric(POWER_VALUE_METRIC)",
        "}",
        "",
        "#[must_use]",
        "pub fn fallback_power_cap(metrics: &AmdSmuMetrics) -> Option<f64> {",
        "    metrics.metric(POWER_CAP_METRIC)",
        "}",
        "",
    ]
    return "\n".join(lines)


GENERATORS = {
    "amd-sensor-adjudication": generate_amd_sensor,
}


def main() -> int:
    index_path = CAIJUEHUB_DIR / "caijue.toml"
    if not index_path.exists():
        print(f"caijue.toml not found at {index_path}")
        return 1

    with index_path.open("rb") as handle:
        index = tomllib.load(handle)

    changed = []
    for entry in index.get("caijue", []):
        if entry.get("line_type") != "rust-strategy":
            continue

        generator = GENERATORS.get(entry["id"])
        if generator is None:
            print(f"skip {entry['id']}: no generator registered")
            continue

        rules_path = CAIJUEHUB_DIR / entry["rules"]
        if not rules_path.exists():
            print(f"skip {entry['id']}: rules {rules_path} not found")
            continue

        with rules_path.open("rb") as handle:
            rules = tomllib.load(handle)

        output_path = REPO_ROOT / entry["implementation"]
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(generator(rules), encoding="utf-8")
        print(
            f"generate {entry['implementation']} "
            f"(type={entry.get('line_type')} approval={entry.get('approval')})"
        )
        changed.append(
            {
                "rules": entry["rules"],
                "implementation": entry["implementation"],
                "approval": entry.get("approval", "auto"),
            }
        )

    print(f"audit: {changed}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
