// ============================================================
// @generated by caijuehub/transcribe.py — DO NOT EDIT BY HAND.
// Edit the rules TOML declared in caijuehub/caijue.toml, then run:
//     python3 caijuehub/transcribe.py
// ============================================================


pub const HELPER_NAME: &str = "resources-battery-threshold";

pub const START_ATTRIBUTE: &str = "charge_control_start_threshold";

pub const END_ATTRIBUTE: &str = "charge_control_end_threshold";

pub const FALLBACK_START_ATTRIBUTE: &str = "charge_start_threshold";

pub const FALLBACK_END_ATTRIBUTE: &str = "charge_stop_threshold";

pub const MINIMUM: u32 = 0;

pub const MAXIMUM: u32 = 100;

pub const STEP: u32 = 5;

pub const DISABLED_START: u32 = 0;

pub const DISABLED_END: u32 = 100;

pub const DEFAULT_START: u32 = 75;

pub const DEFAULT_END: u32 = 80;

pub const NOTIFY_UPOWER: bool = true;
