// ============================================================
// @generated by caijuehub/transcribe.py — DO NOT EDIT BY HAND.
// Edit the rules TOML declared in caijuehub/caijue.toml, then run:
//     python3 caijuehub/transcribe.py
// ============================================================


pub const PORT_PROTOCOLS: &[&str] = &["tcp", "tcp6", "udp", "udp6"];

pub const PORT_LISTEN_ONLY: bool = false;

pub const PORT_SEARCHABLE: bool = true;

pub const SYSTEM_UID_MAX: u32 = 999;

pub const ORPHAN_PARENT_PID: i32 = 1;

pub const ORPHAN_EXCLUDE_COMM: &[&str] = &["systemd"];

pub const DEFAULT_GROUPING: &str = "user";

pub const GROUPING_ORDER: &[&str] = &["user", "app"];
