// ============================================================
// @generated by caijuehub/transcribe.py — DO NOT EDIT BY HAND.
// Edit the rules TOML declared in caijuehub/caijue.toml, then run:
//     python3 caijuehub/transcribe.py
// ============================================================

use crate::caijuehub::smu::AmdSmuMetrics;

pub const SMU_ENABLED: bool = true;

pub const SMU_QUERY_ON_AMD_MISSING_HWMON_POWER: bool = true;

pub const SMU_REFRESH_MODE: &str = "follow-ui-refresh";

pub const SMU_HELPER_NAME: &str = "resources-amdgpu-sensors";

pub const RYZENADJ_PATH: &str = "/usr/local/bin/ryzenadj";

pub const POWER_VALUE_METRIC: &str = "ppt_fast_value";

pub const POWER_CAP_METRIC: &str = "ppt_fast_limit";

pub const GPU_PAGE_SHOW_SLOW_AND_STAPM_ROWS: bool = true;

pub const CPU_PAGE_SHOW_THROTTLE_ROW: bool = true;

pub const CPU_PAGE_SHOW_POWER_WALL_ROW: bool = true;

pub const CPU_TEMPERATURE_FALLBACK: bool = true;

pub const CPU_THERMAL_LIMIT_C: f64 = 95.0;

pub const CPU_POWER_WALL_RATIO: f64 = 0.98;

#[must_use]
pub fn fallback_power_usage(metrics: &AmdSmuMetrics) -> Option<f64> {
    metrics.metric(POWER_VALUE_METRIC)
}

#[must_use]
pub fn fallback_power_cap(metrics: &AmdSmuMetrics) -> Option<f64> {
    metrics.metric(POWER_CAP_METRIC)
}

#[must_use]
pub fn fallback_cpu_temperature(metrics: &AmdSmuMetrics) -> Option<f64> {
    metrics.temperature_c
}
